name: CI Pipeline with GCP Alerts

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
    SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Build
        run: |
          echo "Building project..."
          # simulate failure for demo
          exit 1
          
      - name: Send Slack notification
        if: always() # ensures this runs even if previous steps fail
        uses: actions/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{toJson(steps) }}
          channel: 'oct2022'
